/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  overview: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        'overview/getting-started/intro',
        'overview/getting-started/avalanche-platform-overview',
        'overview/getting-started/avalanche-consensus',
        'overview/getting-started/general-concepts',
        {
          type: 'link',
          label: 'Whitepapers',
          href: 'https://www.avalabs.org/whitepapers',
        },
      ],
    },
    {
      type: 'link',
      label: 'Audits',
      href: 'https://github.com/ava-labs/audits',
    },
  ],

  quickStart: [
    'quickstart/README',
    'quickstart/create-a-local-test-network',
    'quickstart/fuji-workflow',
    'quickstart/avalanche-summit-fuji-quickstart',
    'quickstart/fund-a-local-test-network',
    'quickstart/launch-your-ethereum-dapp',
    'quickstart/transfer-avax-between-x-chain-and-c-chain',
    'quickstart/transfer-avax-between-x-chain-and-p-chain',
    'quickstart/transfer-avax-between-p-chain-and-c-chain',
    'quickstart/transaction-fees',
    'quickstart/adjusting-gas-price-during-high-network-activity',
    'quickstart/sending-transactions-with-dynamic-fees-using-javascript',
    'quickstart/network-runner',
    {
      type: 'category',
      label: 'Exchanges',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'quickstart/exchanges',
        },
      ],
    },
    {
      type: 'category',
      label: 'References',
      items: [
        {
          type: 'autogenerated',
          dirName: 'quickstart/references',
        },
      ],
    },
  ],
  dapps: [
    {
      type: 'category',
      label: 'Smart Contract',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'dapps/smart-contracts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Smart Digital Assets',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'dapps/smart-digital-assets',
        },
      ],
    },
      
  ],
  subnets: [
    {
      type: 'autogenerated',
      dirName: 'subnets',
    },
  ],
  apis: [
    {
      type: 'category',
      label: 'AvalancheGo',
      items: [
        'apis/avalanchego/README',
        {
          type: 'category',
          label: 'APIs',
          collapsed: false,
          items: [
            {
              type: 'autogenerated',
              dirName: 'apis/avalanchego/apis',
            },
          ],
        },
        'apis/avalanchego/public-api-server',
        'apis/avalanchego/postman-avalanche-collection',
        'apis/avalanchego/avalanchego-release-notes',
      ],
    },
    {
      type: 'category',
      label: 'AvalancheJS',
      items: [
        'apis/avalanchejs/README',
        'apis/avalanchejs/api',
        'apis/avalanchejs/create-an-asset-on-the-x-chain',
        'apis/avalanchejs/manage-x-chain-keys',
        'apis/avalanchejs/send-an-asset-on-the-x-chain',
      ],
    },
    {
      type: 'category',
      label: 'Wallet SDK',
      items: [
        {
          type: 'autogenerated',
          dirName: 'apis/avalanche-wallet-sdk',
        },
      ],
    },
  ],
  nodes: [
    'nodes/README',
    {
      type: 'category',
      label: 'Build',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'nodes/build',
        },
      ],
    },
    {
      type: 'category',
      label: 'Maintain',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'nodes/maintain',
        },
        {
          type: 'link',
          label: 'Avalanche Notify',
          href: 'https://notify.avax.network/',
        },
      ],
    },
    {
      type: 'category',
      label: 'Validate',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'nodes/validate',
        },
      ],
    },
  ],
  community: [
    'community/README',
    {
      type: 'link',
      label: 'Product Support',
      href: 'https://support.avax.network/en/',
    },
    {
      type: 'category',
      label: 'Tutorials Contest',
      items: [
        'community/tutorials-contest/README',
      ],
    },
  ],
};

module.exports = sidebars;
