extends: substitution
message: Use '%s' instead of '%s'
level: error
swap:
  "(?i)avalanche[ -]?cli": Avalanche-CLI
  "(?i)subnet[ -]?evm": Subnet-EVM
  "(?i)fuji testnet": Fuji Testnet
  "(?i)fuji": Fuji
  "(?i)avalanchego": AvalancheGo
  "(?i)mainnet": Mainnet
  "(?i)spacesvm": SpacesVM
  "(?i)coreth": Coreth
  "(?i)avalanche network runner": Avalanche Network Runner
  "(?i)subnet[ -]?cli": Subnet-CLI
  "(?i)metamask": MetaMask
  "(?i)chain[ -]?id": ChainID
