extends: substitution
message: Use '%s' instead of '%s'
level: error
exceptions:
  - &timestampvm
  - subnet-evm-tab
  - precompile-evm-tab
swap:
  "(?i)avalanche[ -]?cli": Avalanche-CLI
  "(?i)subnet[ -]?evm": Subnet-EVM
  "(?i)precompile[ -]?evm": Precompile-EVM
  "(?i)fuji testnet": Fuji Testnet
  "(?i)fuji": Fuji
  "(?i)avalanchego": AvalancheGo
  "(?i)mainnet": Mainnet
  "(?i)time[ -]?stamp[ -]?vm": TimestampVM
  "(?i)coreth": Coreth
  "(?i)avalanche network runner": Avalanche Network Runner
  "(?i)subnet[ -]?cli": Subnet-CLI
  "(?i)metamask": MetaMask
  "(?i)chain[ -]?id": ChainID
  "(?i)node[ -]?id": NodeID
  "(?i)github": GitHub
  "(?i)wagmi": WAGMI
  "(?i)subnet[ -]?id": SubnetID
  "(?i)network[ -]?id": NetworkID
  "(?i)c[ -]?chain": C-Chain
  "(?i)p[ -]?chain": P-Chain
  "(?i)x[ -]?chain": X-Chain
