extends: substitution
message: Use '%s' instead of '%s'
level: error
swap:
  "(?i)tx": TX
  "(?i)txs": TXs
  "(?i)hardfork": hard fork
  "(?i)abi": ABI
  "(?i)abis": ABIs
  "(?i)repos?": repository
  "(?i)blackholes?": black hole
