extends: capitalization
message: "'%s' should use title-case capitalization."
link: "https://developers.google.com/style/capitalization#capitalization-in-titles-and-headings"
level: error
scope: heading
match: $title
indicators:
  - ":"
exceptions:
  - AddValidator
  - Avalanche
  - Azure
  - boolean
  - ChainID
  - CLI
  - Code
  - Cosmos
  - Docker
  - duration
  - Emmet
  - EVM
  - float
  - from
  - gRPC
  - I
  - inside
  - int
  - Kubernetes
  - Linux
  - macOS
  - Marketplace
  - MongoDB
  - REPL
  - sayHello()
  - setGreeting()
  - string
  - string, file path
  - Studio
  - Subnet
  - Subnet Creation Wizard
  - Subnets
  - to
  - TypeScript
  - URLs
  - Visual
  - VS
  - with
  - Windows
  - VM
  - uint
  - uint64
  - unit
  - up
