{
 "title": "C-Chain",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Accepted Blocks in Last Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(avalanche_C_blks_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "Accepted"
    }
   ]
  },
  {
   "title": "Rejected Blocks in Last Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(avalanche_C_blks_rejected_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Average Block Acceptance Latency",
   "type": "graph",
   "description": "The average time between a block's issuance and acceptance by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_C_blks_accepted_sum{job=\"avalanchego\"}[5m]) / rate(avalanche_C_blks_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "Avg Acceptance Latency"
    }
   ]
  },
  {
   "title": "Average Block Rejection Latency",
   "type": "graph",
   "description": "The average time between a block's issuance and rejection by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_C_blks_rejected_sum{job=\"avalanchego\"}[5m]) / rate(avalanche_C_blks_rejected_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "Avg Rejection Latency"
    }
   ]
  },
  {
   "title": "Processing Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Transactions" }
   ],
   "targets": [
    {
     "expr": "avalanche_C_blks_processing{job=\"avalanchego\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Percentage of Successful Queries",
   "type": "graph",
   "description": "Percentage of queries for which we receive chits on time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(avalanche_C_handler_chits_count{job=\"avalanchego\"}[2m]) + 1) / (increase(avalanche_C_handler_chits_count{job=\"avalanchego\"}[2m]) + increase(avalanche_C_handler_query_failed_count{job=\"avalanchego\"}[2m]) + 1)",
     "legendFormat": "Queries success"
    }
   ]
  },
  {
   "title": "Message Handling Time (Total)",
   "type": "graph",
   "description": "Measures how much of each second is being spent handling different kinds of messages on the C-Chain.\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "seconds/second" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_C_handler_pull_query_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_C_handler_push_query_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_C_handler_chits_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_C_handler_accepted_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_C_handler_put_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_C_handler_multiput_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_C_handler_get_failed_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_C_handler_query_failed_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_C_handler_get_accepted_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_failed_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors failed"
    }
   ]
  },
  {
   "title": "Message Handling Time (per Message)",
   "type": "graph",
   "description": "Measures how long each kind of request on the C-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_C_handler_pull_query_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_pull_query_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_C_handler_push_query_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_push_query_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_C_handler_chits_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_chits_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_C_handler_accepted_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_accepted_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_get_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_C_handler_put_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_put_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_C_handler_multiput_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_multi_put_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_get_ancestors_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_C_handler_get_failed_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_get_failed_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_C_handler_query_failed_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_query_failed_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_C_handler_get_accepted_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_get_accepted_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_failed_sum{job=\"avalanchego\"}[1m])/rate(avalanche_C_handler_get_ancestors_failed_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors failed"
    }
   ]
  },
  {
   "title": "AVAX Benched",
   "type": "graph",
   "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench.\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avalanche_C_benchlist_benched_weight{job=\"avalanchego\"} / 10^9",
     "legendFormat": "AVAX Benched"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "graph",
   "description": "Measures how long each kind of request on the C-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Messages received/s" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_C_handler_pull_query_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_C_handler_push_query_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_C_handler_chits_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_C_handler_accepted_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_C_handler_put_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_C_handler_multi_put_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_C_handler_get_failed_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_C_handler_query_failed_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_C_handler_get_accepted_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_C_handler_get_ancestors_failed_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors failed"
    }
   ]
  },
  {
   "title": "Possible Problem Indicators (these should return to 0 after a few minutes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }
  },
  {
   "title": "Incoming Messages Dropped in Last Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(avalanche_C_handler_dropped[1m])",
     "legendFormat": "Dropped"
    }
   ]
  },
  {
   "title": "Unprocessed Incoming Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avalanche_C_handler_pending", "legendFormat": "Pending Messages" }
   ]
  },
  {
   "title": "Incoming Messages Expired in Last Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(avalanche_C_handler_expired[1m])",
     "legendFormat": "Expired"
    }
   ]
  },
  {
   "title": "Incoming Messages Throttled in Last Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(avalanche_C_handler_throttled[1m])",
     "legendFormat": "Throttled"
    }
   ]
  },
  {
   "title": "Blocks Pending Issuance ",
   "type": "graph",
   "description": "The number of blocks that are waiting to be issued because of a missing dependency.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avalanche_C_blocked{job=\"avalanchego\"}",
     "legendFormat": "Blocks Pending Issuance"
    }
   ]
  }
 ]
}