{
 "title": "Database",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Database read",
   "type": "graph",
   "description": "Amount read in the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_db_read_size_sum{job=\"avalanchego\"}[1m])",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Database write",
   "type": "graph",
   "description": "Amount written in the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_db_write_size_sum{job=\"avalanchego\"}[1m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Cumulative operations per second",
   "type": "graph",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_db_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_db_get_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_db_delete_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(avalanche_db_has_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(avalanche_db_compact_size_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(avalanche_db_batch_put_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(avalanche_db_batch_delete_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(avalanche_db_batch_reset_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(avalanche_db_batch_replay_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "Cumulative Operations Latency",
   "type": "graph",
   "description": "Measures how long each database operation is taking on average",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(avalanche_db_put_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(avalanche_db_get_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(avalanche_db_delete_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(avalanche_db_has_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_has_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(avalanche_db_compact_size_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_compact_size_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(avalanche_db_batch_put_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_batch_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(avalanche_db_batch_delete_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_batch_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(avalanche_db_batch_reset_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_batch_reset_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(avalanche_db_batch_replay_sum{job=\"avalanchego\"}[5m])/increase(avalanche_db_batch_replay_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "X-Chain operations per second",
   "type": "graph",
   "description": "Measures how many of each database operation is performed each second on X-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_X_db_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_X_db_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_X_db_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(avalanche_X_db_has_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(avalanche_X_db_compact_size_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(avalanche_X_db_batch_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(avalanche_X_db_batch_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(avalanche_X_db_batch_reset_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(avalanche_X_db_batch_replay_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "X-Chain Operations Latency",
   "type": "graph",
   "description": "Measures how long each database operation is taking on average on X-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(avalanche_X_db_put_sum{job=\"avalanchego\"}[5m])/increase(avalanche_X_db_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(avalanche_X_db_get_sum{job=\"avalanchego\"}[5m])/increase(avalanche_X_db_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(avalanche_X_db_delete_sum{job=\"avalanchego\"}[5m])/increase(avalanche_X_db_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(avalanche_X_db_has_sum{job=\"avalanchego\"}[5m])/increase(avalanche_X_db_has_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(avalanche_X_db_compact_size_sum{job=\"avalanchego\"}[5m])/increase(avalanche_X_db_compact_size_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(avalanche_X_db_batch_put_sum{job=\"avalanchego\"}[5m])/increase(avalanche_X_db_batch_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(avalanche_X_db_batch_delete_sum{job=\"avalanchego\"}[5m])/increase(avalanche_X_db_batch_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(avalanche_X_db_batch_reset_sum{job=\"avalanchego\"}[5m])/increase(avalanche_X_db_batch_reset_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(avalanche_X_db_batch_replay_sum{job=\"avalanchego\"}[5m])/increase(avalanche_X_db_batch_replay_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "P-Chain operations per second",
   "type": "graph",
   "description": "Measures how many of each database operation is performed each second on P-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_P_db_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_P_db_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_P_db_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(avalanche_P_db_has_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(avalanche_P_db_compact_size_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(avalanche_P_db_batch_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(avalanche_P_db_batch_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(avalanche_P_db_batch_reset_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(avalanche_P_db_batch_replay_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "P-Chain Operations Latency",
   "type": "graph",
   "description": "Measures how long each database operation is taking on average on P-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(avalanche_P_db_put_sum{job=\"avalanchego\"}[5m])/increase(avalanche_P_db_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(avalanche_P_db_get_sum{job=\"avalanchego\"}[5m])/increase(avalanche_P_db_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(avalanche_P_db_delete_sum{job=\"avalanchego\"}[5m])/increase(avalanche_P_db_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(avalanche_P_db_has_sum{job=\"avalanchego\"}[5m])/increase(avalanche_P_db_has_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(avalanche_P_db_compact_size_sum{job=\"avalanchego\"}[5m])/increase(avalanche_P_db_compact_size_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(avalanche_P_db_batch_put_sum{job=\"avalanchego\"}[5m])/increase(avalanche_P_db_batch_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(avalanche_P_db_batch_delete_sum{job=\"avalanchego\"}[5m])/increase(avalanche_P_db_batch_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(avalanche_P_db_batch_reset_sum{job=\"avalanchego\"}[5m])/increase(avalanche_P_db_batch_reset_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(avalanche_P_db_batch_replay_sum{job=\"avalanchego\"}[5m])/increase(avalanche_P_db_batch_replay_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "C-Chain operations per second",
   "type": "graph",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_C_db_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_C_db_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_C_db_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(avalanche_C_db_has_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(avalanche_C_db_compact_size_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(avalanche_C_db_batch_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(avalanche_C_db_batch_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(avalanche_C_db_batch_reset_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(avalanche_C_db_batch_replay_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "C-Chain Operations Latency",
   "type": "graph",
   "description": "Measures how long each database operation is taking on average on C-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "increase(avalanche_C_db_put_sum{job=\"avalanchego\"}[5m])/increase(avalanche_C_db_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(avalanche_C_db_get_sum{job=\"avalanchego\"}[5m])/increase(avalanche_C_db_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(avalanche_C_db_delete_sum{job=\"avalanchego\"}[5m])/increase(avalanche_C_db_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(avalanche_C_db_has_sum{job=\"avalanchego\"}[5m])/increase(avalanche_C_db_has_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(avalanche_C_db_compact_size_sum{job=\"avalanchego\"}[5m])/increase(avalanche_C_db_compact_size_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(avalanche_C_db_batch_put_sum{job=\"avalanchego\"}[5m])/increase(avalanche_C_db_batch_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(avalanche_C_db_batch_delete_sum{job=\"avalanchego\"}[5m])/increase(avalanche_C_db_batch_delete_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(avalanche_C_db_batch_reset_sum{job=\"avalanchego\"}[5m])/increase(avalanche_C_db_batch_reset_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(avalanche_C_db_batch_replay_sum{job=\"avalanchego\"}[5m])/increase(avalanche_C_db_batch_replay_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  }
 ]
}