{
 "title": "Avalanche General",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Peer Count",
   "type": "graph",
   "description": "Number of network peers the node is connected to",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avalanche_peers{job=\"avalanchego\"}",
     "legendFormat": "Peers connected"
    }
   ]
  },
  {
   "title": "Network Timing",
   "type": "graph",
   "description": "Network timeout is dynamic parameter indicating how long will node wait for response, latency is the actual time to response.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avalanche_network_timeout/1000000000",
     "legendFormat": "Timeout"
    },
    {
     "expr": "avalanche_avg_network_latency/1000000000",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "graph",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_accepted_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_get_accepted_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_get_accepted_frontier_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(avalanche_get_ancestors_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_put_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_multi_put_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_get_version_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(avalanche_get_peerlist_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(avalanche_pull_query_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_push_query_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_version_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(avalanche_ping_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(avalanche_pong_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(avalanche_get_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get"
    }
   ]
  },
  {
   "title": "Messages Sent per Second",
   "type": "graph",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_accepted_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_get_accepted_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_get_accepted_frontier_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(avalanche_get_ancestors_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_put_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_multi_put_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_get_version_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(avalanche_get_peerlist_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(avalanche_pull_query_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_push_query_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_version_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(avalanche_ping_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(avalanche_pong_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "pong"
    },
    {
     "expr": "rate(avalanche_get_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get"
    }
   ]
  },
  {
   "title": "Messages Failed per Second",
   "type": "graph",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_accepted_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_get_accepted_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_get_accepted_frontier_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted frontier"
    },
    {
     "expr": "rate(avalanche_get_ancestors_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_put_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_multi_put_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_get_version_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "get version"
    },
    {
     "expr": "rate(avalanche_get_peerlist_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "get peerlist"
    },
    {
     "expr": "rate(avalanche_pull_query_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_push_query_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_version_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "version"
    },
    {
     "expr": "rate(avalanche_ping_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "ping"
    },
    {
     "expr": "rate(avalanche_pong_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "pong"
    }
   ]
  },
  {
   "title": "Benched stake",
   "type": "graph",
   "description": "Amount of the stake in AVAX that is benched (ignored) because the nodes are unhealthy",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avalanche_X_benchlist_benched_weight/1000000000",
     "legendFormat": "X chain"
    },
    {
     "expr": "avalanche_P_benchlist_benched_weight/1000000000",
     "legendFormat": "P Chain"
    },
    {
     "expr": "avalanche_C_benchlist_benched_weight/1000000000",
     "legendFormat": "C Chain"
    }
   ]
  }
 ]
}