{
 "title": "X-Chain",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Vertices in Last Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(avalanche_X_vtx_accepted_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(avalanche_X_vtx_rejected_count{job=\"avalanchego\"}[1m]))",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Average Vertex Latency",
   "type": "graph",
   "description": "The average time between a vertex's issuance and acceptance by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_X_vtx_accepted_sum{job=\"avalanchego\"}[5m]) / rate(avalanche_X_vtx_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "Accepted"
    },
    {
     "expr": "rate(avalanche_X_vtx_rejected_sum{job=\"avalanchego\"}[5m]) / rate(avalanche_X_vtx_rejected_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Processing Vertices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avalanche_X_tx_processing{job=\"avalanchego\"}",
     "legendFormat": "Transactions"
    },
    {
     "expr": "avalanche_X_vtx_processing{job=\"avalanchego\"}",
     "legendFormat": "Vertices"
    }
   ]
  },
  {
   "title": "Percentage of Successful Queries",
   "type": "graph",
   "description": "Percentage of queries for which we receive chits on time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(avalanche_X_handler_chits_count{job=\"avalanchego\"}[1m]) + 1) / (increase(avalanche_X_handler_chits_count{job=\"avalanchego\"}[1m]) + increase(avalanche_X_handler_query_failed_count{job=\"avalanchego\"}[1m]) + 1)",
     "legendFormat": "Success pct"
    }
   ]
  },
  {
   "title": "Message Handling Time (Total)",
   "type": "graph",
   "description": "Measures how much of each second is being spent handling different kinds of messages on the X-Chain.\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "seconds/second" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_X_handler_pull_query_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_X_handler_push_query_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_X_handler_chits_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_X_handler_accepted_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_X_handler_put_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_X_handler_multiput_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_X_handler_get_failed_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_X_handler_query_failed_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_X_handler_get_accepted_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_failed_sum{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors failed"
    }
   ]
  },
  {
   "title": "Message Handling Time (per Message)",
   "type": "graph",
   "description": "Measures how long each kind of request on the X-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_X_handler_pull_query_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_pull_query_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_X_handler_push_query_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_push_query_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_X_handler_chits_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_chits_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_X_handler_accepted_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_accepted_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_get_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_X_handler_put_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_put_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_X_handler_multiput_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_multi_put_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_get_ancestors_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_X_handler_get_failed_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_get_failed_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_X_handler_query_failed_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_query_failed_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_X_handler_get_accepted_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_get_accepted_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_failed_sum{job=\"avalanchego\"}[1m])/rate(avalanche_X_handler_get_ancestors_failed_count{job=\"avalanchego\"}[1m])/1000000000",
     "legendFormat": "get ancestors failed"
    }
   ]
  },
  {
   "title": "AVAX Benched",
   "type": "graph",
   "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench.\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avalanche_X_benchlist_benched_weight{job=\"avalanchego\"} / 10^9",
     "legendFormat": "AVAX Benched"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "graph",
   "description": "Measures how many of each kind of message are received per second on the X-Chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Messages received/s" }
   ],
   "targets": [
    {
     "expr": "rate(avalanche_X_handler_pull_query_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(avalanche_X_handler_push_query_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(avalanche_X_handler_chits_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(avalanche_X_handler_accepted_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(avalanche_X_handler_put_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(avalanche_X_handler_multi_put_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(avalanche_X_handler_get_failed_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(avalanche_X_handler_query_failed_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(avalanche_X_handler_get_accepted_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(avalanche_X_handler_get_ancestors_failed_count{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors failed"
    }
   ]
  },
  {
   "title": "Possible Problem Indicators (these should return to 0 after a few minutes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "Incoming Messages Dropped in Last Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(avalanche_X_handler_dropped[1m])",
     "legendFormat": "Dropped"
    }
   ]
  },
  {
   "title": "Unprocessed Incoming Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avalanche_X_handler_pending", "legendFormat": "Pending Messages" }
   ]
  },
  {
   "title": "Incoming Messages Expired in Last Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(avalanche_X_handler_expired[1m])",
     "legendFormat": "Expired"
    }
   ]
  },
  {
   "title": "Throttled Messages in Last Minute",
   "type": "graph",
   "description": "Number of incoming messages dropped due to rate-limiting.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(avalanche_X_handler_throttled_pool_alloc_exhausted[1m]) + increase(avalanche_X_handler_throttled_pool_empty[1m]) + increase(avalanche_X_handler_throttled_validator_alloc_exhausted[1m])",
     "legendFormat": "Throttled Messages"
    }
   ]
  }
 ]
}