---
- name: Remove a typical reddev developement server
  hosts: localhost
  vars_prompt:
    - name: instance_name
      prompt: Instance name
      private: no
  tasks:
    - name: Get Confirmation
      pause:
        prompt: Please confirm you want to remove the instance [{{ instance_name }}]! Press return to continue. Press Ctrl+c and then a to abort
    - name: Removing the instance [{{ instance_name }}]
      vultr_server:
        name: "{{ instance_name }}"
        api_account: reddev
        state: absent
    - meta: refresh_inventory
