# .github/workflows/gpt-translate.yml
name: Ava Docs Translate

on:
  issue_comment:
    types: [created]

jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ava Docs Translate
        if: contains(github.event.comment.body, '/gt')
        uses: meaghanfitzgerald/ava-docs-translate@v0.1.31
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: "ft:gpt-3.5-turbo-0613:personal:docs-es-101823:8B47qlat"
          prompt: 'Please translate the following text into naturalistic {targetLanguage}.'
