# .github/workflows/gpt-translate.yml
name: Ava Docs Translate

on:
  issue_comment:
    types: [ created ]

jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3        

      - name: Run Ava Docs Translate
        if: |
          contains(github.event.comment.body, '/gt')
        uses: meaghanfitzgerald/ava-docs-translate@v0.1.3
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          prompt: 'While the following keywords must be left in English: ["Avalanche", "Fuji", "Faucet", "Warp Messaging"] please translate the following into naturalistic {targetLanguage}'
